image: ruby:2.3

variables:
  JEKYLL_ENV: production
stages:
  - build-website
  - build-wiki
  - deploy


compilation-website:
  stage: build-website
  before_script:
  - bundle install
  script:
  - bundle exec jekyll build -d public
  artifacts:
    paths:
    - public
    
compilation-wiki:
  stage: build-wiki
  image: node:alpine
  before_script:
  - npm install natives@1.1.6
  - npm install -g gitbook-cli
  - cd wiki
  - gitbook install ./
  script:
  - gitbook build . ../public/wiki
  artifacts:
    paths:
    - public/wiki


pages:
  stage: deploy
  # Docker image with tools to deploy to EOS
  image: gitlab-registry.cern.ch/ci-tools/ci-web-deployer:latest
  script:
  - deploy-eos
  dependencies:
    - compilation-website
    - compilation-wiki
  only:
  - master@websites/patatrack-website

