site_name: Patatrack Wiki
theme: 
    name: material
    highlightjs: true
    hljs_languages:
        - C++
        - python
        - bash
        - CUDA
site_dir: public/wiki
docs_dir: wiki


extra_javascript:
  - 'extra.js'
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

markdown_extensions:
    - pymdownx.arithmatex
    - admonition
    - codehilite

nav:
    - Home: index.md
    - Public Results:
        - Public Plots April 2019: publicPlots_201904.md
    - Development for Patatrack: 
        - Patatrack development: PatatrackDevelopment.md
        - Installing Patatrack releases: PatatrackReleases.md
        - Running the validation: PatatrackValidation.md
        - An introduction to CUDA in CMSSW: CUDAinCMSSW.md
        - Profiling cmsRun on a remote machine with the NVIDIA Visual Profiler: Remote_profiling_with_NVVP/Remote_profiling_with_NVVP.md
        - Creating an "empty" CMSSW release: emptyrelease.md
        - CUDA to HIP: CUDAtoHIP.md
    - CPU and GPU Workflows:
        - Workflows: workflows.md
        - Workflows for Connecting The Dots 2019: workflows_CTD19.md
    - Benchmarking:
        - Stall Service: benchmarking_stall_service.md
        - CMSSW Scalability: cmssw_scalability.md
        - CUDA Utilities: CUDA_Utilities.md
        - MPS set up: MPS-setup.md
    - Benchmarking the HLT:
        - HLT menu and data: HLTTiming.md
        - Using the DAQ source: DAQSource.md
    - Performance Portability:
        - Alpaka and Cupla: AlpakaAndCupla.md
        - CUDA to cupla: cuda2cupla.md
        - CUDA to Alpaka: cuda2alpaka.md
        - CUDA to HIP: CUDAtoHIP.md
        - SYCL LLVM compiler: SYCL.md
        - CUDA to cupla: cuda2cupla.md 
    - External libraries: 
        - Libraries: libraries.md
    - Training: 
        - Tracker Knowledge Transfer (December 2019) - [part 1, CUDA]: cuda_training_dpg_12_2019.md
        - Tracker Knowledge Transfer (December 2019) - [part 2, CMSSW] : cuda_training_dpg_12_2019_part2.md
        - Tracker Knowledge Transfer (December 2019) - [part 3, CMSSW] : cuda_training_dpg_12_2019_part3.md
